export enum KeyMap {
  ENTER = 'Enter',
  ESCAPE = 'Escape',
  SPACE = 'Space',
  TAB = 'Tab',
  ARROW_UP = 'ArrowUp',
  ARROW_DOWN = 'ArrowDown',
  ARROW_LEFT = 'ArrowLeft',
  ARROW_RIGHT = 'ArrowRight',
  HOME = 'Home',
  END = 'End',
  PAGE_UP = 'PageUp',
  PAGE_DOWN = 'PageDown',
  BACKSPACE = 'Backspace',
  DELETE = 'Delete',
  SHIFT = 'Shift',
  CONTROL = 'Control',
  ALT = 'Alt',
  META = 'Meta',
  CAPS_LOCK = 'CapsLock',
  NUM_LOCK = 'NumLock',
  PRINT_SCREEN = 'PrintScreen',
  INSERT = 'Insert',
}
